FROM jenkins/inbound-agent:latest

USER root

# Install curl, apt-transport-https, and gnupg
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg

# Install Google Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
    && apt-get update && apt-get install -y google-cloud-sdk kubectl

USER jenkins