FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
    && apt-get update && apt-get install -y google-cloud-sdk kubectl

# Install gke-gcloud-auth-plugin
RUN apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

# Ensure plugin is in PATH
RUN ln -s /usr/lib/google-cloud-sdk/bin/gke-gcloud-auth-plugin /usr/bin/gke-gcloud-auth-plugin

USER jenkins