name: Local DockerHub K8s CI

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_PASS }}

      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USER/backend:$BUILD_NUMBER server
          docker push $DOCKERHUB_USER/backend:$BUILD_NUMBER

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKERHUB_USER/frontend:$BUILD_NUMBER client
          docker push $DOCKERHUB_USER/frontend:$BUILD_NUMBER

      - name: Update image tags in K8s manifests
        run: |
          sed -i "s|image: .*/backend:.*|image: $DOCKERHUB_USER/backend:$BUILD_NUMBER|g" server/server-deployment.yaml
          sed -i "s|image: .*/frontend:.*|image: $DOCKERHUB_USER/frontend:$BUILD_NUMBER|g" client/client-deployment.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to local Kubernetes
        run: |
          kubectl apply -f server/server-deployment.yaml
          kubectl apply -f server/server-service.yaml
          kubectl apply -f client/client-deployment.yaml
          kubectl apply -f client/client-service.yaml
          kubectl rollout restart deploy client-deployment || true
          kubectl rollout restart deploy server-deployment || true
